language: python
python: 
  - "3.7"

addons:
  - chrome: stable

install:
  - pip install -r requirements.txt

env:
  global:
    - DRIVER=selenium_chrome
    - CHROME_BIN=/usr/bin/google-chrome

before_install:
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - sudo dpkg -i google-chrome*.deb


script:
  - "python3 TestSidebarLinks.py"