language: python
sudo: required
python: 
  - "3.7"

addons:
  - chrome: stable

before_script:
  - wget https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.7.1/bin/
  - export CHROME_BIN=chromium-browser

install:
  - pip install -r requirements.txt
 
script:
  - "python3 TestSidebarLinks.py"