language: python
sudo: required
python: 
  - "3.7"

addons:
  - chrome: stable

before_script:
- sudo apt-get update
- sudo apt-get install dbus-x11
- export DISPLAY=:99.0
- export CHROME_BIN=/usr/bin/google-chrome
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
- wget https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo cp chromedriver /usr/bin

services:
  - xvfb

install:
  - pip install -r requirements.txt
 
script:
  - "python3 TestSidebarLinks.py"